### ISSUE TITLE
Console [youtube] spam when a song is complete and nothing is queued.

### ISSUE THREAD

**Issue by zytho** [SexualRhinoceros/MusicBot#4]
The console constantly is spammed by multiple things when a song completes.

![error](http://i.imgur.com/7tHXYsQ.png)

**Comment by hdmifish** [comment]
I found that this was when ffmpeg.exe could not be launched (norton blocked it on my computer). Make sure ffmpeg.exe is in the directory.

**Comment by zytho** [comment]
my ffmpeg is in the directory and is working. otherwise the music wouldn't be played

**Comment by SexualRhinoceros** [comment]
This is because its playing a song thats silent over and over. Add something to the queue and this spam will stop
