### ISSUE TITLE
[ffmpeg] correcting container hang

### ISSUE THREAD

**Issue by hdmifish** [SexualRhinoceros/MusicBot#7]
I have found an issue, fairly easy to recreate. It seems its triggered by skipping a song after enterng a !play link that doesnt work. Such as typing !play playlidt (playlidt is not a valid URL). 

The bot loads the next song normally, and starts up ffmpeg but it just says correcting container, and no music plays through.  This happens with both empty and populated queues.

**Comment by SexualRhinoceros** [comment]
Just updated the bot should remove all false errors from playing the non existing music link
